### ISSUE TITLE
youtube.com - problematyczne 3 lub 4 kafle

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters#1721]
Jak ktoś nie chce czekać na 5 kafli, a ma 3-4 wielkie kafle na YouTube:

```css
youtube.com#$#[style] * { --ytd-rich-grid-items-per-row: 5; }
youtube.com#$#ytd-video-meta-block[rich-meta] #channel-name.ytd-video-meta-block, ytd-video-meta-block[rich-meta] #metadata-line.ytd-video-meta-block { font-size: 1.3rem !important; }
youtube.com#$##title.ytd-rich-grid-renderer, #title.ytd-rich-shelf-renderer { font-size: 1.6rem !important; }
```

lub

```css
@-moz-document domain("youtube.com") {
[style] * {
    --ytd-rich-grid-items-per-row: 5;
    --ytd-rich-grid-posts-per-row: 3;
    --ytd-rich-grid-movies-per-row: 7;
}


ytd-video-meta-block[rich-meta] #channel-name.ytd-video-meta-block,
ytd-video-meta-block[rich-meta] #metadata-line.ytd-video-meta-block {
    font-size: 1.3rem;
}

#title.ytd-rich-grid-renderer,
#title.ytd-rich-shelf-renderer {
    font-size: 1.6rem;
}
}
```
