### ISSUE TITLE
e-remiza.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishAnnoyanceFilters#2302]
![capture_370_27-06-2020_23-25-52](https://user-images.githubusercontent.com/63287518/85932591-95d82b80-b8cd-11ea-902a-993bace8b649.gif)

**Comment by blocker999** [comment]
a co z tym ?

**Comment by hawkeye116477** [comment]
@blocker999 W sumie chciałeś przecież chować promocje nowych wydań, choć nie wiem czy ten news da się jakoś ładnie schować.

**Comment by krystian3w** [comment]
ładnie się nie da, nie ma jak w uBO sprawdzać czy `post 406` to dalej e-gazeta (lub czy nie zmienili go na inny wpis) i na podstawie tego próbować robić układ 2 kolumnowy.

Takie coś by wymagało częstego sprawdzania:

```css
.tcol-md-4.tcol-sm-4.tcol-xs-6.tcol-ss-12.b_item.kad_blog_item[style] {
width: 50%;
}
/* komplikacja RWD - obliczanie JS-em jakiegoś wymiaru w pozycjonowaniu absolutnym */
.tcol-md-4.tcol-sm-4.tcol-xs-6.tcol-ss-12.b_item.kad_blog_item[style*="733"] {
left: 580px;
}
```

Przy używaniu `:remove()` to post przy zmianie wielkości okna lata z 2 linii do pierwszej.
